# Generated by Django 4.0.3 on 2022-03-12 10:46

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('phoneNo', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='foodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-veg')], default='Veg', max_length=20)),
                ('price', models.IntegerField()),
                ('customization', multiselectfield.db.fields.MultiSelectField(choices=[('Cheese', 'Cheese'), ('Butter', 'Butter'), ('Onion toppings', 'Onion toppings'), ('mayonnaise', 'mayonnaise'), ('spicy', 'spicy'), ('extra chilly spicy', 'extra chilly spicy')], max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploadedImages')),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfTables', models.IntegerField()),
                ('availableTables', models.IntegerField()),
                ('bookedTables', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('post', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTables', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('paymentStatus', models.BooleanField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.customer')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfFood', models.IntegerField()),
                ('totalCost', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('paymentStatus', models.BooleanField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.customer')),
            ],
        ),
        migrations.CreateModel(
            name='orderood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pricePerItem', models.IntegerField()),
                ('custmizations', models.CharField(choices=[('Cheese', 'Cheese'), ('Butter', 'Butter'), ('Onion toppings', 'Onion toppings'), ('mayonnaise', 'mayonnaise'), ('spicy', 'spicy'), ('extra chilly spicy', 'extra chilly spicy')], max_length=60)),
                ('totalPrice', models.IntegerField()),
                ('foodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.customer')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.orders')),
            ],
        ),
        migrations.CreateModel(
            name='mannualOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFname', models.CharField(max_length=100)),
                ('customerLname', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('foodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.customer')),
                ('foodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='dealsAndOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerCode', models.CharField(max_length=8)),
                ('discount', models.CharField(max_length=5)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('foodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.fooditems')),
            ],
        ),
    ]
