# Generated by Django 4.0.3 on 2022-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_fooditems_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='uname',
            field=models.CharField(default='fake', max_length=100),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='category',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.FileField(upload_to='uploadedImages'),
        ),
    ]
