# Generated by Django 4.0.3 on 2022-03-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_remove_customer_id_customer_uname_fooditems_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='uname',
            field=models.CharField(default='fake+', max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
