# Generated by Django 4.0.3 on 2022-04-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_remove_orderood_custmizations_alter_orderood_foodid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderood',
            name='name',
            field=models.CharField(default='xyz', max_length=20),
        ),
    ]
